# SwiftLint Configuration for DiskDevil
# https://github.com/realm/SwiftLint

# Enabled rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - opening_brace
  - line_length  # We handle this with custom configuration below

# Paths to exclude
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - Tests/LinuxMain.swift
  - "*/Generated/*"

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - to
    - ip
    - vm

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_print_in_production:
    name: "No print() in production code"
    regex: "\\bprint\\s*\\("
    message: "Use Logger instead of print() for production code"
    severity: warning
    match_kinds:
      - identifier

  force_unwrap_warning:
    name: "Force Unwrap Warning"
    regex: "\\w+!"
    message: "Consider using optional binding or nil coalescing instead of force unwrapping"
    severity: warning
    match_kinds:
      - identifier

reporter: "xcode"
